### ISSUE TITLE
About your Model3d

### ISSUE THREAD

**Issue by neilwth** [YogangSingh/Solution-to-Equations-of-Motion-for-Underwater-Glider#2]
Hi there,

I downloaded your codes and found that it seemed to have only 2D models inside, although the title of the files are 3D. The variation of yaw and roll cannot be simulated with the current codes. 

Is there anything to modify before using the codes to simulate the yaw/roll angle? Or perhaps these files are not the final version corresponding to the PhD thesis of J. G. Graver (I saw excellent simulations about the lateral dynamics in the thesis)? If not, is it possible for me to ask for a final version?

Thanks a lot!

Neil

**Comment by YogangSingh** [comment]
Hello,

Thanks for the mail !!

The codes only simulate the 2D motion of the glider at the moment. Since
our work was not to replicate the Graver work but to benchmark a part of it
and use it for experimental verification with numerical results.

These results are published in :

*Y. Singh*, Bhattacharyya, S.K. and Idichandy, V.G. "CFD Approach to
Modelling, Hydrodynamic Analysis and Motion Characteristics of a Laboratory
Underwater Glider with Experimental Results
<https://scholar.google.com/scholar?oi=bibs&cluster=8235063458000419082&btnI=1&hl=en>
". *Journal of Ocean Engineering and Sciences*, 2(2), 2017, Pages 90-119,
ISSN 2468-0133 2017.(DOI:https://doi.org/10.1016/j.joes.2017.03.003 ).

If you are interested in roll and yaw dynamics, you need to incorporate a
few more equations mentioned in Graver work along with few more variables
like side slip angle etc. You can then use any numerical method to solve
these first order couple differential equations.

Unfortunately this is the final version we used.
Hope that answers your question .

Do not hesitate to contact if you have any questions.

Best wishes,
Yogang

**Comment by neilwth** [comment]
Hi Yogang,

Thanks very much for your reply!

Best regards,
Neil

**Comment by neilwth** [comment]
Hi Yogang,

Thanks very much for your reply!

Best regards,
Neil
